import Head from 'next/head';
import Input from '../components/atoms/Input/Input';
import Header from '../components/molecules/Header/Header';
export default function Home() {
  const testChange = (event: any) => {
    console.log(event.target.value);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Input
        onChange={testChange}
        fontSize="2rem"
        placeholder={'테스트입니당'}
        borderRadius="1rem"
      ></Input>

      <div>테스트 잘 보이시나요?</div>
    </>
  );
}
