import Head from 'next/head';
import Input from '../components/atoms/Input/Input';
import MapView from '../components/organisms/mapView/mapView';
export default function Home() {
  const testChange = (event: any) => {
    console.log(event.target.value);
  };
  const MapInfo = [
    { x: 37.3595704, y: 127.105399, name: '카페1', id: 1 },
    { x: 37.3693404, y: 127.305399, name: '카페2', id: 99 },
    { x: 37.3594704, y: 127.207699, name: '카페3', id: 23 },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=j9mxfv8xtx"
        />
      </Head>

      <Input
        onChange={testChange}
        fontSize="2rem"
        placeholder={'테스트입니당'}
        borderRadius="1rem"
      ></Input>
      <MapView mapInfo={MapInfo}></MapView>
      <div>테스트 잘 보이시나요?</div>
    </>
  );
}
