import Head from 'next/head';
import Pin from '../../components/atoms/Pin/Pin';

export default function Home() {
  const onClickPin = () => {
    console.log('pin을 클릭함');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>atoms test용 페이지</div>
      <Pin content={'세상에서 제일 작은 카페'} onClick={onClickPin}></Pin>
    </>
  );
}
