import Head from 'next/head';
import Label from '../../components/atoms/Label/Label';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>atoms test용 페이지</div>
      <Label color={'red'} content={'LABEL'} />
    </>
  );
}
